# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1297b15e389d7535f3cf7961cca5fce7cdc23ebcce47d09fb7733cb81dd6dccb5da13cb7f88097afa60ad3ba96cb4a13857f95c6d30d293a38d7eb53f0ed0f91

test:
  secret_key_base: b91aa05df6f31c6db360cfdce744ffd9ae7b772ccf60e345b4e67ff48da62fee0cfd1f30f83ef0b7b7bcc98cb3b118433c79aab6f96a722e3aee4350b03f9168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
